{
  "assignee": null, 
  "assignees": [], 
  "author_association": "MEMBER", 
  "body": "When RabbitMQ becomes unreachable the request agent crashes repeatedly, until systemd gives up on trying to restart it. It should have graceful handling of connection interruptions and retry logic.\n\n```\nOct 18 15:22:49 gratiav2-1 systemd[1]: graccreq.service holdoff time over, scheduling restart.\nOct 18 15:22:49 gratiav2-1 systemd[1]: Started GRACC Request Agent.\nOct 18 15:22:49 gratiav2-1 systemd[1]: Starting GRACC Request Agent...\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: DEBUG:pika.adapters.select_connection:Using EPollPoller\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2b5f0e0>>, 'only': None, 'one_s\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2b5f098>>, 'only': None, 'one_s\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2b5f128>>, 'only': None, 'one_s\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: DEBUG:pika.callback:Added: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x2b5cd10>>, 'only': None, \nOct 18 15:22:49 gratiav2-1 graccreq[2753]: INFO:pika.adapters.base_connection:Connecting to 129.79.53.45:5672\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: WARNING:pika.adapters.base_connection:Connection to 129.79.53.45:5672 failed: [Errno 111] Connection refused\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: INFO:pika.adapters.base_connection:Connecting to 2001:18e8:2:6::10e:5672\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: WARNING:pika.adapters.base_connection:Connection to 2001:18e8:2:6::10e:5672 failed: [Errno 101] Network is unreachable\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: WARNING:pika.connection:Could not connect, 0 attempts left\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: DEBUG:pika.callback:Processing 0:_on_connection_error\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2b5f0e0>> for \"0:_on_connection_error\"\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: Traceback (most recent call last):\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: File \"/usr/bin/graccreq\", line 9, in <module>\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: load_entry_point('graccreq==2.2', 'console_scripts', 'graccreq')()\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: File \"/usr/lib/python2.7/site-packages/graccreq/OverMind.py\", line 106, in main\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: overmind.run()\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: File \"/usr/lib/python2.7/site-packages/graccreq/OverMind.py\", line 37, in run\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: self.createConnection()\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: File \"/usr/lib/python2.7/site-packages/graccreq/OverMind.py\", line 56, in createConnection\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: self._conn = pika.adapters.blocking_connection.BlockingConnection(self.parameters)\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: File \"/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py\", line 339, in __init__\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: self._process_io_for_connection_setup()\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: File \"/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py\", line 374, in _process_io_for_connection_setup\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: self._open_error_result.is_ready)\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: File \"/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py\", line 395, in _flush_output\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: raise exceptions.ConnectionClosed()\nOct 18 15:22:49 gratiav2-1 graccreq[2753]: pika.exceptions.ConnectionClosed\nOct 18 15:22:49 gratiav2-1 systemd[1]: graccreq.service: main process exited, code=exited, status=1/FAILURE\nOct 18 15:22:49 gratiav2-1 systemd[1]: Unit graccreq.service entered failed state.\nOct 18 15:22:49 gratiav2-1 systemd[1]: graccreq.service failed.\nOct 18 15:22:50 gratiav2-1 systemd[1]: graccreq.service holdoff time over, scheduling restart.\nOct 18 15:22:50 gratiav2-1 systemd[1]: start request repeated too quickly for graccreq.service\nOct 18 15:22:50 gratiav2-1 systemd[1]: Failed to start GRACC Request Agent.\nOct 18 15:22:50 gratiav2-1 systemd[1]: Unit graccreq.service entered failed state.\nOct 18 15:22:50 gratiav2-1 systemd[1]: graccreq.service failed.\n```\n", 
  "closed_at": null, 
  "closed_by": null, 
  "comments": 0, 
  "comments_url": "https://api.github.com/repos/opensciencegrid/gracc-request/issues/38/comments", 
  "created_at": "2016-10-18T17:51:51Z", 
  "events_url": "https://api.github.com/repos/opensciencegrid/gracc-request/issues/38/events", 
  "html_url": "https://github.com/opensciencegrid/gracc-request/issues/38", 
  "id": 183757641, 
  "labels": [], 
  "labels_url": "https://api.github.com/repos/opensciencegrid/gracc-request/issues/38/labels{/name}", 
  "locked": false, 
  "milestone": null, 
  "number": 38, 
  "repository_url": "https://api.github.com/repos/opensciencegrid/gracc-request", 
  "state": "open", 
  "title": "Request agent crashes when unable to contact RabbitMQ", 
  "updated_at": "2016-10-18T17:51:51Z", 
  "url": "https://api.github.com/repos/opensciencegrid/gracc-request/issues/38", 
  "user": {
    "avatar_url": "https://avatars1.githubusercontent.com/u/1627510?v=4", 
    "events_url": "https://api.github.com/users/retzkek/events{/privacy}", 
    "followers_url": "https://api.github.com/users/retzkek/followers", 
    "following_url": "https://api.github.com/users/retzkek/following{/other_user}", 
    "gists_url": "https://api.github.com/users/retzkek/gists{/gist_id}", 
    "gravatar_id": "", 
    "html_url": "https://github.com/retzkek", 
    "id": 1627510, 
    "login": "retzkek", 
    "organizations_url": "https://api.github.com/users/retzkek/orgs", 
    "received_events_url": "https://api.github.com/users/retzkek/received_events", 
    "repos_url": "https://api.github.com/users/retzkek/repos", 
    "site_admin": false, 
    "starred_url": "https://api.github.com/users/retzkek/starred{/owner}{/repo}", 
    "subscriptions_url": "https://api.github.com/users/retzkek/subscriptions", 
    "type": "User", 
    "url": "https://api.github.com/users/retzkek"
  }
}
