{
  "assignee": null, 
  "assignees": [], 
  "author_association": "MEMBER", 
  "body": "When RabbitMQ becomes unreachable the periodic summary agent crashes repeatedly, until systemd gives up on trying to restart it. It should have graceful handling of connection interruptions and retry logic.\n\n```\nOct 18 15:28:00 gratiav2-1 systemd[1]: graccsumperiodic.service holdoff time over, scheduling restart.\nOct 18 15:28:00 gratiav2-1 systemd[1]: Started GRACC Periodic Summarizer Agent.\nOct 18 15:28:00 gratiav2-1 systemd[1]: Starting GRACC Periodic Summarizer Agent...\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:root:Starting query to remote requster\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:pika.adapters.select_connection:Using EPollPoller\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2f13c68>>, 'only': None\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2f13ab8>>, 'only': None\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2f13f80>>, 'only': None\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:pika.callback:Added: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x2f18850>>, 'only'\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: INFO:pika.adapters.base_connection:Connecting to 129.79.53.45:5672\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: ERROR:pika.adapters.base_connection:Connection to 129.79.53.45:5672 failed: timeout\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: INFO:pika.adapters.base_connection:Connecting to 2001:18e8:2:6::10e:5672\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: WARNING:pika.adapters.base_connection:Connection to 2001:18e8:2:6::10e:5672 failed: [Errno 101] Network is unreachable\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: WARNING:pika.connection:Could not connect, 0 attempts left\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:pika.callback:Processing 0:_on_connection_error\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x2f13c68>> for \"0:_on_connection_err\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: Traceback (most recent call last):\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/bin/graccsumperiodic\", line 9, in <module>\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: load_entry_point('graccsum==1.2', 'console_scripts', 'graccsumperiodic')()\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/graccsum/periodic_summarizer.py\", line 63, in main\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: summary_agent.run()\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/graccsum/periodic_summarizer.py\", line 49, in run\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: self.runRules()\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/graccsum/periodic_summarizer.py\", line 37, in runRules\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: destination_key=self._config['PeriodicSummarizer']['destination_key'])\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/graccreq/client.py\", line 144, in query\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: self._createConn()\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/graccreq/client.py\", line 83, in _createConn\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: self.conn = pika.adapters.blocking_connection.BlockingConnection(parameters)\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py\", line 339, in __init__\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: self._process_io_for_connection_setup()\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py\", line 374, in _process_io_for_connection_setup\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: self._open_error_result.is_ready)\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: File \"/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py\", line 395, in _flush_output\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: raise exceptions.ConnectionClosed()\nOct 18 15:28:01 gratiav2-1 graccsumperiodic[2941]: pika.exceptions.ConnectionClosed\nOct 18 15:28:01 gratiav2-1 systemd[1]: graccsumperiodic.service: main process exited, code=exited, status=1/FAILURE\nOct 18 15:28:01 gratiav2-1 systemd[1]: Unit graccsumperiodic.service entered failed state.\nOct 18 15:28:01 gratiav2-1 systemd[1]: graccsumperiodic.service failed.\nOct 18 15:28:01 gratiav2-1 systemd[1]: graccsumperiodic.service holdoff time over, scheduling restart.\nOct 18 15:28:01 gratiav2-1 systemd[1]: start request repeated too quickly for graccsumperiodic.service\nOct 18 15:28:01 gratiav2-1 systemd[1]: Failed to start GRACC Periodic Summarizer Agent.\nOct 18 15:28:01 gratiav2-1 systemd[1]: Unit graccsumperiodic.service entered failed state.\nOct 18 15:28:01 gratiav2-1 systemd[1]: graccsumperiodic.service failed.\n```\n", 
  "closed_at": null, 
  "closed_by": null, 
  "comments": 0, 
  "comments_url": "https://api.github.com/repos/opensciencegrid/gracc-summary/issues/8/comments", 
  "created_at": "2016-10-18T17:53:09Z", 
  "events_url": "https://api.github.com/repos/opensciencegrid/gracc-summary/issues/8/events", 
  "html_url": "https://github.com/opensciencegrid/gracc-summary/issues/8", 
  "id": 183757955, 
  "labels": [], 
  "labels_url": "https://api.github.com/repos/opensciencegrid/gracc-summary/issues/8/labels{/name}", 
  "locked": false, 
  "milestone": null, 
  "number": 8, 
  "repository_url": "https://api.github.com/repos/opensciencegrid/gracc-summary", 
  "state": "open", 
  "title": "Summary agent crashes when unable to contact RabbitMQ", 
  "updated_at": "2016-10-18T17:53:09Z", 
  "url": "https://api.github.com/repos/opensciencegrid/gracc-summary/issues/8", 
  "user": {
    "avatar_url": "https://avatars1.githubusercontent.com/u/1627510?v=4", 
    "events_url": "https://api.github.com/users/retzkek/events{/privacy}", 
    "followers_url": "https://api.github.com/users/retzkek/followers", 
    "following_url": "https://api.github.com/users/retzkek/following{/other_user}", 
    "gists_url": "https://api.github.com/users/retzkek/gists{/gist_id}", 
    "gravatar_id": "", 
    "html_url": "https://github.com/retzkek", 
    "id": 1627510, 
    "login": "retzkek", 
    "organizations_url": "https://api.github.com/users/retzkek/orgs", 
    "received_events_url": "https://api.github.com/users/retzkek/received_events", 
    "repos_url": "https://api.github.com/users/retzkek/repos", 
    "site_admin": false, 
    "starred_url": "https://api.github.com/users/retzkek/starred{/owner}{/repo}", 
    "subscriptions_url": "https://api.github.com/users/retzkek/subscriptions", 
    "type": "User", 
    "url": "https://api.github.com/users/retzkek"
  }
}
